# Generated by Django 3.1 on 2020-09-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default=1, max_length=100, verbose_name='makale img'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(),
        ),
    ]
